# .github/workflows/deploy.yml
name: Serverless website Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-infrastructure-and-app:
    runs-on: ubuntu-latest

    steps:
      # Clones the repository to the GitHub Actions runner
      - name: Checkout Code
        uses: actions/checkout@v4

      # Authenticates with AWS using repository secrets for S3 and CloudFront access
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: us-east-1 #change this to your desired AWS region
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Installs Terraform CLI and authenticates via TF_API_TOKEN with the wrapper disabled
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false

      # Initializes the Terraform working directory and backend
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      # Applies the infrastructfure changes automatically without manual approval
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

      # Extracts S3 bucket name and CloudFront ID from Terraform state into environment variables
      - name: Extract Terraform Outputs
        id: tf_outputs
        working-directory: ./terraform
        run: |
          echo "BUCKET_NAME=$(terraform output -raw s3_bucket_name)" >> $GITHUB_ENV
          echo "CLOUDFRONT_ID=$(terraform output -raw cloudfront_distribution_id)" >> $GITHUB_ENV

      # Uploads the application files to the S3 bucket using native shell variables 
      - name: Sync file to S3
        run: |
          aws s3 sync ./ s3://$BUCKET_NAME --exclude ".git/*" --exclude "terraform/*" --exclude ".github/*" --exclude "asset/*" --exclude ".gitignore" --exclude "LICENSE" --exclude "README.md"
      # Invalidates the CloudFront cache to deploy the latest HTML/CSS updates
      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"